#!/bin/bash
#
# Scheduling script, that times recording of wspr transmissions
# Copyright (C) 2016-present  Clemens Heese / PA7T <pa7t@wsprlive.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

while true
	do sleep 1
		#echo `date`" Sleeping ..."
		SECONDS=`date +%S`
		if [ $(( `date +%M | sed 's/^0//'` % 2)) -eq 0 ]
		then
			#echo 'Sleeping for '`expr 120 - $SECONDS`' s'
			sleep `expr 120 - $SECONDS`
		else
			#echo 'Sleeping for '`expr 60 - $SECONDS`' s'
			sleep `expr 60 - $SECONDS`	
		fi
		#echo "Starting recording with nohup in background"
		nohup sh /opt/redpitaya/www/apps/sdr_wspr/decode-wspr-parallel.sh  >> /dev/shm/sdr-wspr.log 2>&1 &
done
